### PR TITLE
Run DistributedMapper tests and support for gtsam 4.0+

### PR DESCRIPTION
**Pull request by akashsharma02**
@itzsid Please review the changes I've made to support the latest GTSAM

I thought it was safe/correct to remove the _Anchor Keys_ after optimization. 

However, I still have a few test cases which fail, i.e., the error observed between centralized solution and distribution don't match up.

### CODE REVIEW

**Comment by itzsid** [comment]
@akashsharma02 Mostly looks good. Which all tests current fail? 

You can try the distributed mapper on the older version of GTSAM using the docker: 
```
docker pull awilby/distributed_mapper:latest
docker run awilby/distributed_mapper --nrRobots 4 --dataDir ../../data/example_4robots/
```

Can you also check the outputs of the following datasets: 
```
$ ./runDistributedMapper --nrRobots 4 --dataDir ../../data/example_4robots/
$ ./runDistributedMapper --nrRobots 9 --dataDir ../../data/example_9robots/
$ ./runDistributedMapper --nrRobots 16 --dataDir ../../data/example_16robots/
$ ./runDistributedMapper --nrRobots 25 --dataDir ../../data/example_25robots/
$ ./runDistributedMapper --nrRobots 36 --dataDir ../../data/example_36robots/
$ ./runDistributedMapper --nrRobots 49 --dataDir ../../data/example_49robots/
```

**Comment by akashsharma02** [comment]
@itzsid 

Apologize for the late reply. It seems that there was a change in key anchor value from "Z9999999" to "99999999" in GTSAM.

Everything magically worked after I made that change, I also removed some other defined constants, which are available from GTSAM. 

All test cases now pass. Please do review the changes and let me know if anything else is required

**Comment by itzsid** [comment]
@akashsharma02 No issues, thanks for checking it. Can you update the README.md with the new GTSAM installation instructions which worked for you? Specify the actuall commit id for GTSAM. 

If possible update the Dockerfile and push a docker image as well since it is the easiest to try out but not needed immediately as well. 

Do we need the `*optimizedTUM.txt` files pushed in this PR?

**Comment by akashsharma02** [comment]
@itzsid I have updated the README (tested build and run with the updated commit id) and removed the `*_optimizedTUM.txt` files.

I've updated with the same commit id on docker but have not tested/pushed the docker image as I don't really know how to do that. 

Thanks!

**Comment by itzsid** [comment]
Great, thanks! The docker file can be updated in later PRs. I'll merge this PR.

**Pull request merged**
